
package cs.vt.edu.bdd.test;

import org.junit.*;
import org.junit.Assert;

import cs.vt.edu.bdd.examples.AtmAccount;


/**
 * Auto-Generated test class created by SmartBDD
 * 
 */
public class AtmAccountTest {


    /**
     * Test method generated by SmartBDD
     * 
     */
    @Test
    public void testDepositFailure()
        throws Exception
    {
        AtmAccount atmAccount = new AtmAccount(100.0D);
        atmAccount.deposit(20.0D);
        Assert.assertEquals(atmAccount.getBalance(), 110.0D, 0.0D);
    }

    /**
     * Test method generated by SmartBDD
     * 
     */
    @Test
    public void testWithdrawSuccess()
        throws Exception
    {
        AtmAccount atmAccount = new AtmAccount(100.0D);
        atmAccount.withdraw(20.0D);
        Assert.assertEquals(atmAccount.getBalance(), 80.0D, 0.0D);
    }

    /**
     * Test method generated by SmartBDD
     * 
     */
    @Test
    public void testWithdrawFailure()
        throws Exception
    {
        AtmAccount atmAccount = new AtmAccount(100.0D);
        atmAccount.withdraw(20.0D);
        Assert.assertEquals(atmAccount.getBalance(), 90.0D, 0.0D);
        Assert.assertEquals(atmAccount.getBalance(), 250.0D, 0.0D);
    }

}
