
package cs.vt.edu.bdd.test;

import org.junit.*;
import org.junit.Assert;

import cs.vt.edu.bdd.examples.Stack;


/**
 * Auto-Generated test class created by SmartBDD
 * 
 */
public class StackTest {


    /**
     * Test method generated by SmartBDD
     * 
     */
    @Test
    public void testPushInAStack()
        throws Exception
    {
        Stack stack = new Stack(100);
        stack.push(10);
        stack.push(20);
        Assert.assertEquals(stack.size(), 2);
    }

    /**
     * Test method generated by SmartBDD
     * 
     */
    @Test
    public void testPushAndPopInStack()
        throws Exception
    {
        Stack stack = new Stack();
        stack.push(10);
        Assert.assertEquals(stack.pop(), 10);
    }

}
