
package cs.vt.edu.bdd.test;

import org.junit.*;
import org.junit.Assert;

import cs.vt.edu.bdd.examples.WebRequester;


/**
 * Auto-Generated test class created by SmartBDD
 * 
 */
public class WebRequesterTest {


    /**
     * Test method generated by SmartBDD
     * 
     */
    @Test
    public void testSendRequestToValidUrl()
        throws Exception
    {
        WebRequester webRequester = new WebRequester();
        webRequester.sendRequest("http://www.google.com");
        Assert.assertTrue(webRequester.responseContains("google"));
    }

    /**
     * Test method generated by SmartBDD
     * 
     */
    @Test
    public void testSendRequestToInvalidUrl2()
        throws Exception
    {
        WebRequester webRequester = new WebRequester("http://www.google.com");
        webRequester.sendRequest();
        Assert.assertTrue(webRequester.responseContains("google"));
    }

}
