package cs.vt.edu.bdd.generator;

public class JunitTestCodeConstants {

	//The package to put the test unit code in.
	public static final String JUNIT_TEST_CLASS_PACKAGE = "cs.vt.edu.bdd.test";
	
	public static final String JUNIT_BASE_PACKAGE = "org.junit.Test";
	
	public static final String JUNIT_METHOD_TEST_ANNOTATION = "Test";
	
	//The source folder for the source code of project.
	public static final String PROJECT_BASE_SOURCE = "src";
	
	//The default comment for the class.
	public static final String DEFAULT_CLASS_LEVEL_COMMENT = "Auto-Generated test class created by SmartBDD";
	public static final String DEFAULT_METHOD_LEVEL_COMMENT = "Test method generated by SmartBDD";
	
	public static final String TEST_EXTENTION = "Test";

	public static final String JUNIT_TESTCASE_PACKAGE = "junit.framework.TestCase";
}
